# Generated by Django 5.2.8 on 2025-11-29 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_review"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
